/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package au.edu.swin.ict.road.designer.smc.validation;

import au.edu.swin.ict.road.designer.smc.Constraint;
import au.edu.swin.ict.road.designer.smc.TaskRef;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link au.edu.swin.ict.road.designer.smc.BehaviorTerm}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BehaviorTermValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validateExtension(String value);
	boolean validateExtends(String value);
	boolean validateIsAbstract(boolean value);
	boolean validateTaskRef(EList<TaskRef> value);
	boolean validateConstraint(EList<Constraint> value);
}
