/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package au.edu.swin.ict.road.designer.smc.validation;

import au.edu.swin.ict.road.designer.smc.Role;
import au.edu.swin.ict.road.designer.smc.Term;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link au.edu.swin.ict.road.designer.smc.Contract}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContractValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validateName(String value);
	boolean validateType(String value);
	boolean validateRuleFile(String value);
	boolean validateRoleAID(Role value);
	boolean validateRoleBID(Role value);
	boolean validateDescription(String value);
	boolean validateAbstract(boolean value);
	boolean validateState(String value);
	boolean validateTerm(EList<Term> value);
}
