/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package au.edu.swin.ict.road.designer.smc.validation;

import au.edu.swin.ict.road.designer.smc.MessageType;
import au.edu.swin.ict.road.designer.smc.Operation;
import au.edu.swin.ict.road.designer.smc.Parameter;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link au.edu.swin.ict.road.designer.smc.OutMsg}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OutMsgValidator {
	boolean validate();

	boolean validateDeliveryType(MessageType value);

	boolean validateDeliveryType(String value);
	boolean validateOpName(String value);
	boolean validateTransformation(String value);
	boolean validateIsResponse(boolean value);

	boolean validateOperation(Operation value);

	boolean validateOutMsg(EList<Parameter> value);
	boolean validateSrcMsg(EList<String> value);
}
