/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package au.edu.swin.ict.road.designer.smc.validation;

import au.edu.swin.ict.road.designer.smc.BehaviorTerm;
import au.edu.swin.ict.road.designer.smc.Constraint;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link au.edu.swin.ict.road.designer.smc.ProcessDefinition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProcessDefinitionValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validateDescr(String value);
	boolean validateCoS(String value);
	boolean validateCoT(String value);
	boolean validateConstraint(EList<Constraint> value);
	boolean validateBehaviorTerm(EList<BehaviorTerm> value);
}
