/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package au.edu.swin.ict.road.designer.smc.validation;

import au.edu.swin.ict.road.designer.smc.BehaviorTerm;
import au.edu.swin.ict.road.designer.smc.Contract;
import au.edu.swin.ict.road.designer.smc.Fact;
import au.edu.swin.ict.road.designer.smc.MessageAnalyzer;
import au.edu.swin.ict.road.designer.smc.PlayerBinding;
import au.edu.swin.ict.road.designer.smc.ProcessDefinition;
import au.edu.swin.ict.road.designer.smc.Role;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link au.edu.swin.ict.road.designer.smc.SMC}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SMCValidator {
	boolean validate();

	boolean validateRole(EList<Role> value);
	boolean validateContract(EList<Contract> value);
	boolean validateProcessDefinition(EList<ProcessDefinition> value);
	boolean validateBehaviorTerm(EList<BehaviorTerm> value);
	boolean validatePlayerBinding(EList<PlayerBinding> value);
	boolean validateMessageAnalyzer(EList<MessageAnalyzer> value);
	boolean validateRulesDir(String value);
	boolean validateRoutingRuleFile(String value);
	boolean validateCompositeRuleFile(String value);
	boolean validateOrganizerBinding(String value);
	boolean validateDescription(String value);
	boolean validateFact(EList<Fact> value);
}
