/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package au.edu.swin.ict.road.designer.smc.validation;

import au.edu.swin.ict.road.designer.smc.Task;

/**
 * A sample validator interface for {@link au.edu.swin.ict.road.designer.smc.TaskRef}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TaskRefValidator {
	boolean validate();

	boolean validatePreEP(String value);
	boolean validatePostEP(String value);
	boolean validatePerformanceVal(String value);
	boolean validateTask(Task value);
}
